services:
  database:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin123
#      MYSQL_USER: admin
#      MYSQL_PASSWORD: admin123
      MYSQL_DATABASE: database
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - mysql-volume-2:/var/lib/mysql
#    healthcheck:
#        test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
#        timeout: 5s
#        retries: 10

volumes:
  mysql-volume-2: