services:
  database:
    hostname: ${MYSQL_HOST}
    image: mysql:8.0
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
#      MYSQL_USER: ${MYSQL_USER}
#      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB_NAME}
    ports:
      - "127.0.0.1:3306:${MYSQL_PORT}"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql-volume-2:/var/lib/mysql
    healthcheck:
        test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
        timeout: 5s
        retries: 10

  mongo:
    image: mongo:noble
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - ./mongo-data:/data/db

volumes:
  mysql-volume-2: